version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      TWEETSPHERE_DB__uri: "postgresql://postgres:postgres@db:5432/${TWEETSPHERE_DB:-tweetsphere}"
      TWEETSPHERE_DB__connect_args: "{}"
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    build: postgres
    image: tweetsphere_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/pamps_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DBS=tweetsphere, tweetsphere_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
