name: FastAPI Tests Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    env:
      TWEETSPHERE_DB: "tweetsphere_test"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -r requirements.txt

      - name: Starts container
        run: TWEETSPHERE_DB=tweetsphere_test docker-compose up -d

      - name: Base Migration
        run: docker-compose exec api alembic stamp base

      - name: Upgrades Migration
        run: docker-compose exec api alembic upgrade head

      - name: Execute tests
        run: docker-compose exec api pytest -v -l --tb=short --maxfail=1 tests/

      - name: Stops container
        run: docker-compose down
